name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Deploy on pushes to the main branch. Adjust this if needed.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_PROJECT_ID }}-docker.pkg.dev

      - name: Build and Push Docker Image to Artifact Registry
        run: |
          IMAGE_URI="${{ secrets.GCP_PROJECT_ID }}-docker.pkg.dev/ecoroots-artifact-registry/${{ secrets.CLOUD_RUN_SERVICE_NAME }}:$(date +%Y%m%d-%H%M%S)"
          docker build \
            --build-arg DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
            --build-arg DATABASE_USER=${{ secrets.DATABASE_USER }} \
            --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            --build-arg GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME}}
            -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --image "$IMAGE_URI" \
            --platform managed \
            --region ${{ secrets.CLOUD_RUN_REGION }} \
            --allow-unauthenticated
